
namespace Core.Entities
{
    public class CustomerBasket
    {
        public CustomerBasket()
        {
            
        }
        public CustomerBasket(string id)
        {
            Id=id;
        }
        public string Id { get; set; } //generated by client side
        public List<BasketItems> Items{ get; set; }=new List<BasketItems>();
    }
}